language: node_js
node_js:
  - 10.13
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache: npm
before_install: []
before_script:
  - npm prune
  - npm install -g --production coveralls codecov
script:
  - npm run cover
  - npm run lint
  - npm run docs
after_script:
  - codecov
  - cat ./coverage/lcov.info | coveralls
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
